/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rpc/cw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpc Cw Endpoint
         * @description RPC - Dosage selon Cw (%).
         *
         *     The request body must match RpcCwInputs:
         *       - category
         *       - general (GeneralInfo)
         *       - residue (ResidueProps)
         *       - binder_system (BinderSystem)
         *       - num_recipes, containers_per_recipe, safety_factor
         *       - solids_mass_pct, saturation_pct
         *       - binder_mass_pct_recipes (list of % liant for each recette)
         *
         *     This endpoint simply:
         *       1. Lets FastAPI + Pydantic validate data
         *       2. Calls the domain solver solve_rpc_cw(...)
         *       3. Returns the MixDesignResult to the client
         */
        post: operations["rpc_cw_endpoint_rpc_cw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/wb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpc Wb Endpoint
         * @description RPC/RPG - Rapport eau/ciment (W/C).
         */
        post: operations["rpc_wb_endpoint_rpc_wb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/slump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpc Slump Endpoint
         * @description RPC - Ajustement pour slump (prédiction Cw%).
         */
        post: operations["rpc_slump_endpoint_rpc_slump_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/essai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpc Essai Endpoint
         * @description RPC - Méthode essai-erreur (ajustements masse/eau).
         */
        post: operations["rpc_essai_endpoint_rpc_essai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpg/cw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpg Cw Endpoint
         * @description RPG - Dosage selon Cw% (Paste Aggregate Fill).
         *     Requires aggregate_fraction_pct (A_m%) and aggregate_specific_gravity.
         */
        post: operations["rpg_cw_endpoint_rpg_cw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpg/wb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpg Wb Endpoint
         * @description RPG - Rapport eau/ciment W/C (Paste Aggregate Fill).
         *     Requires aggregate_fraction_pct (A_m%) and aggregate_specific_gravity.
         */
        post: operations["rpg_wb_endpoint_rpg_wb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpg/essai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rpg Essai Endpoint
         * @description RPG - Méthode essai-erreur (Paste Aggregate Fill).
         *     Applies mass adjustments to a base RPG recipe (Cw or W/C).
         *     Supports added_aggregate_mass in addition to residue and water adjustments.
         */
        post: operations["rpg_essai_endpoint_rpg_essai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rrc/dosage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rrc Dosage Endpoint
         * @description RRC/CRF — dosage par Bw (liant/roches stériles) et W/C du coulis.
         *     Formules du cours, Dias 66-70 (masses, retardateur de prise, coulis).
         */
        post: operations["rrc_dosage_endpoint_rrc_dosage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BinderComponent
         * @description Un composant de liant (un ciment) dans le système de liant.
         *     'mass_fraction' = fraction massique de ce ciment par rapport au liant total (0–1).
         */
        BinderComponent: {
            /** Type */
            type: string;
            /**
             * Specific Gravity
             * @description Poids spécifique (SG) du ciment (sans unité).
             */
            specific_gravity: number;
            /**
             * Mass Fraction
             * @description Fraction massique du ciment dans le liant total (0–1). La somme de toutes les fractions doit être égale à 1.
             */
            mass_fraction: number;
        };
        /**
         * BinderSystem
         * @description Système de liant contenant 1 à MAX_BINDER_COMPONENTS composants (ciments).
         */
        BinderSystem: {
            /** Components */
            components: components["schemas"]["BinderComponent"][];
        };
        /**
         * ContainerType
         * @description Type de géométrie du contenant de moulage.
         *     Le frontend envoie ces valeurs exactes dans 'general.container_type'.
         * @enum {string}
         */
        ContainerType: "section_hauteur" | "rayon_hauteur" | "longueur_largeur_hauteur" | "volume";
        /**
         * GeneralInfo
         * @description Informations générales renseignées sur la page d'accueil.
         *     Correspond à useStore().general côté frontend.
         */
        GeneralInfo: {
            /**
             * Operator Name
             * @description Nom de l'opérateur qui prépare la recette.
             */
            operator_name?: string | null;
            /**
             * Project Name
             * @description Nom du projet / chantier.
             */
            project_name?: string | null;
            /**
             * Residue Id
             * @description Identifiant du résidu (ex: code labo).
             */
            residue_id?: string | null;
            /**
             * Mix Date
             * @description Date de mélange au format YYYY-MM-DD (on garde une string pour l'instant).
             */
            mix_date?: string | null;
            /** @description Type de contenant utilisé pour le moulage. */
            container_type?: components["schemas"]["ContainerType"] | null;
            /**
             * Container Section
             * @description Section du contenant en cm² (si type 'section_hauteur').
             */
            container_section?: number | null;
            /**
             * Container Height
             * @description Hauteur du contenant en cm.
             */
            container_height?: number | null;
            /**
             * Container Radius
             * @description Rayon du contenant en cm (si type 'rayon_hauteur').
             */
            container_radius?: number | null;
            /**
             * Container Length
             * @description Longueur du contenant en cm (si type 'longueur_largeur_hauteur').
             */
            container_length?: number | null;
            /**
             * Container Width
             * @description Largeur du contenant en cm (si type 'longueur_largeur_hauteur').
             */
            container_width?: number | null;
            /**
             * Container Volume M3
             * @description Volume du contenant en m³ (si type 'volume', saisi directement).
             */
            container_volume_m3?: number | null;
            /**
             * Binder Count
             * @description Nombre de ciments dans le liant (1 à 8). Écho ; voir binder_system.
             */
            binder_count?: number | null;
            /**
             * Binder1 Type
             * @description Type du ciment 1 (CP50, CP10, etc.). Écho des 3 premiers.
             */
            binder1_type?: string | null;
            /**
             * Binder2 Type
             * @description Type du ciment 2 (optionnel). Écho.
             */
            binder2_type?: string | null;
            /**
             * Binder3 Type
             * @description Type du ciment 3 (optionnel). Écho.
             */
            binder3_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MixCategory
         * @description Catégorie de remblai.
         *     - RPC : Remblai en pâte cimenté
         *     - RPG : Remblai pâte granulaire
         *     - RRC : Remblai rocheux
         * @enum {string}
         */
        MixCategory: "RPC" | "RPG" | "RRC";
        /**
         * MixComponentMass
         * @description Masses des différents composants d'une recette de remblai.
         *     Toutes les masses sont en kg.
         *
         *     Les champs *_to_add_* sont utilisés par la méthode essai-erreur pour indiquer
         *     les masses supplémentaires à ajouter par rapport à la recette de base.
         */
        MixComponentMass: {
            /** Residue Dry Mass Kg */
            residue_dry_mass_kg: number;
            /** Residue Wet Mass Kg */
            residue_wet_mass_kg: number;
            /** Binder Total Mass Kg */
            binder_total_mass_kg: number;
            /** Binder C1 Mass Kg */
            binder_c1_mass_kg: number;
            /** Binder C2 Mass Kg */
            binder_c2_mass_kg: number;
            /** Binder C3 Mass Kg */
            binder_c3_mass_kg: number;
            /** Water Total Mass Kg */
            water_total_mass_kg: number;
            /** Water To Add Mass Kg */
            water_to_add_mass_kg: number;
            /**
             * Aggregate Dry Mass Kg
             * @default 0
             */
            aggregate_dry_mass_kg: number;
            /**
             * Binder To Add Mass Kg
             * @default 0
             */
            binder_to_add_mass_kg: number;
            /**
             * Binder C1 To Add Mass Kg
             * @default 0
             */
            binder_c1_to_add_mass_kg: number;
            /**
             * Binder C2 To Add Mass Kg
             * @default 0
             */
            binder_c2_to_add_mass_kg: number;
            /**
             * Binder C3 To Add Mass Kg
             * @default 0
             */
            binder_c3_to_add_mass_kg: number;
            /** Binder Masses Kg */
            binder_masses_kg?: number[];
            /** Binder To Add Masses Kg */
            binder_to_add_masses_kg?: number[];
        };
        /**
         * MixDesignResult
         * @description Résultat global renvoyé par un solveur (CW, WB, Slump, Essai-erreur).
         *     Contient:
         *       - la catégorie (RPC/RPG/RRC)
         *       - la méthode (dosage_cw, wb, slump, essai)
         *       - les infos générales
         *       - la liste de recettes calculées
         */
        MixDesignResult: {
            category: components["schemas"]["MixCategory"];
            method: components["schemas"]["RpcMethod"];
            general: components["schemas"]["GeneralInfo"];
            /** Recipes */
            recipes: components["schemas"]["MixState"][];
        };
        /**
         * MixState
         * @description Résumé de l'état d'une recette de remblai après calcul.
         *     Tu pourras enrichir cette classe (porosité, compacité, etc.) plus tard.
         */
        MixState: {
            /** Bulk Density Kg M3 */
            bulk_density_kg_m3: number;
            /** Dry Density Kg M3 */
            dry_density_kg_m3: number;
            /** Solids Mass Pct */
            solids_mass_pct: number;
            /** Saturation Pct */
            saturation_pct: number;
            /** Wc Ratio */
            wc_ratio: number;
            /** Bw Mass Pct */
            bw_mass_pct: number;
            /** Bv Vol Pct */
            bv_vol_pct: number;
            /** Cv Vol Pct */
            cv_vol_pct: number;
            /** W Mass Pct */
            w_mass_pct: number;
            /** Void Ratio */
            void_ratio: number;
            /** Porosity */
            porosity: number;
            /** Theta Pct */
            theta_pct: number;
            /** Gs Binder */
            gs_binder: number;
            /** Gs Backfill */
            gs_backfill: number;
            /** Bulk Unit Weight Kn M3 */
            bulk_unit_weight_kN_m3: number;
            /** Dry Unit Weight Kn M3 */
            dry_unit_weight_kN_m3: number;
            /** Container Volume M3 */
            container_volume_m3: number;
            /** Total Backfill Volume M3 */
            total_backfill_volume_m3: number;
            /**
             * Residue Volume M3
             * @default 0
             */
            residue_volume_m3: number;
            /**
             * Binder Volume M3
             * @default 0
             */
            binder_volume_m3: number;
            /**
             * Water Volume M3
             * @default 0
             */
            water_volume_m3: number;
            /**
             * Solid Volume M3
             * @default 0
             */
            solid_volume_m3: number;
            /**
             * Void Volume M3
             * @default 0
             */
            void_volume_m3: number;
            /**
             * Aggregate Volume M3
             * @default 0
             */
            aggregate_volume_m3: number;
            /**
             * Aggregate Vol Pct Of Residue
             * @default 0
             */
            aggregate_vol_pct_of_residue: number;
            /**
             * Aggregate Vol Pct Of Backfill
             * @default 0
             */
            aggregate_vol_pct_of_backfill: number;
            /**
             * Aggregate Mass Pct
             * @default 0
             */
            aggregate_mass_pct: number;
            components: components["schemas"]["MixComponentMass"];
        };
        /**
         * ResidueProps
         * @description Propriétés du résidu.
         *     Tous les pourcentages ici sont des % massiques (0–100).
         */
        ResidueProps: {
            /**
             * Specific Gravity
             * @description Poids spécifique (SG) du résidu (sans unité).
             */
            specific_gravity: number;
            /**
             * Moisture Mass Pct
             * @description Teneur en eau massique du résidu humide, en % (ex: 20 pour 20%).
             */
            moisture_mass_pct: number;
        };
        /**
         * RpcCwInputs
         * @description Entrées pour la méthode RPC – Dosage selon Cw%.
         */
        RpcCwInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /**
             * Solids Mass Pct
             * @description % massique de solides dans le remblai (Cw%).
             */
            solids_mass_pct: number;
            /**
             * Saturation Pct
             * @description Degré de saturation S_r (%) du remblai.
             */
            saturation_pct: number;
            /**
             * Binder Mass Pct Recipes
             * @description Pourcentage massique de liant dans chaque recette (%). La liste doit contenir au moins num_recipes éléments (jusqu'à 4).
             */
            binder_mass_pct_recipes: number[];
            /**
             * Aggregate Fraction Pct
             * @description Fraction massique d'agrégat co-mixing (%). Si 0 -> aucun agrégat.
             * @default 0
             */
            aggregate_fraction_pct: number | null;
            /**
             * Aggregate Specific Gravity
             * @description Masse volumique spécifique (Gs) de l'agrégat. Optionnel.
             */
            aggregate_specific_gravity?: number | null;
        };
        /**
         * RpcEssaiAdjustment
         * @description Ajustements appliqués à une recette lors de la méthode essai-erreur.
         *
         *     Valeurs positives = ajout
         *     Valeurs négatives = retrait
         */
        RpcEssaiAdjustment: {
            /**
             * Added Dry Residue Mass
             * @description Masse de résidu sec ajoutée (kg).
             * @default 0
             */
            added_dry_residue_mass: number;
            /**
             * Added Wet Residue Mass
             * @description Masse de résidu humide ajoutée (kg).
             * @default 0
             */
            added_wet_residue_mass: number;
            /**
             * Added Water Mass
             * @description Masse d'eau ajoutée (kg).
             * @default 0
             */
            added_water_mass: number;
        };
        /**
         * RpcEssaiInputs
         * @description Entrées pour la méthode RPC – Essai-erreur.
         *
         *     On part d'une recette de base (calculée par CW ou W/B),
         *     puis on applique des ajustements (ajout/retrait d'eau, résidu, etc.).
         */
        RpcEssaiInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /** @description Méthode utilisée pour la recette de base (CW ou WB en pratique). */
            base_method: components["schemas"]["RpcMethod"];
            base_inputs_cw?: components["schemas"]["RpcCwInputs"] | null;
            base_inputs_wb?: components["schemas"]["RpcWbInputs"] | null;
            /**
             * Adjustments
             * @description Liste des ajustements (un par recette).
             */
            adjustments: components["schemas"]["RpcEssaiAdjustment"][];
        };
        /**
         * RpcMethod
         * @description Méthode de calcul pour la catégorie RPC (et plus tard RPG).
         *     Les valeurs correspondent à ce que le frontend utilise déjà.
         * @enum {string}
         */
        RpcMethod: "dosage_cw" | "wb" | "slump" | "essai";
        /**
         * RpcSlumpInputs
         * @description Entrées pour la méthode RPC – Ajustement pour slump.
         */
        RpcSlumpInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /**
             * Cone Type
             * @description Type de cône d'Abrams utilisé (mini ou grand).
             * @default mini
             * @enum {string}
             */
            cone_type: "mini" | "grand";
            /**
             * Slump Mm
             * @description Slump cible en mm (ex: 180 mm).
             */
            slump_mm: number;
            /**
             * Saturation Pct
             * @description Degré de saturation S_r (%) du remblai.
             */
            saturation_pct: number;
            /**
             * Binder Mass Pct Recipes
             * @description Pourcentage massique de liant pour chaque recette (%).
             */
            binder_mass_pct_recipes: number[];
        };
        /**
         * RpcWbInputs
         * @description Entrées pour la méthode RPC – rapport eau/ciment (W/C).
         *
         *     Dans ton C#, tu utilisais la valeur -99 pour signifier :
         *       'le programme calcule W/C automatiquement'.
         *     Ici on fait plus propre :
         *       - si wc_ratio_recipes est None, le solver le calcule
         *       - si wc_ratio_recipes est fourni, on utilise ces valeurs imposées
         */
        RpcWbInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /**
             * Saturation Pct
             * @description Degré de saturation S_r (%) du remblai.
             */
            saturation_pct: number;
            /**
             * Binder Mass Pct Recipes
             * @description Pourcentage massique de liant pour chaque recette (%).
             */
            binder_mass_pct_recipes: number[];
            /**
             * Wc Ratio Recipes
             * @description Rapport eau/ciment imposé pour chaque recette. Si None -> le solveur le calcule à partir des autres paramètres.
             */
            wc_ratio_recipes?: number[] | null;
        };
        /**
         * RpgCwInputs
         * @description Entrées pour la méthode RPG — Dosage selon Cw%.
         *     Identique à RpcCwInputs mais aggregate_fraction_pct et
         *     aggregate_specific_gravity sont obligatoires.
         */
        RpgCwInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /**
             * Solids Mass Pct
             * @description % massique de solides dans le remblai (Cw%).
             */
            solids_mass_pct: number;
            /**
             * Saturation Pct
             * @description Degré de saturation Sr (%).
             */
            saturation_pct: number;
            /**
             * Binder Mass Pct Recipes
             * @description Bw% (liant / (résidu+agrégat)) pour chaque recette.
             */
            binder_mass_pct_recipes: number[];
            /**
             * Aggregate Fraction Pct
             * @description A_m% — fraction massique d'agrégat dans les solides non-liant (Ma/(Ma+Mr)*100).
             */
            aggregate_fraction_pct: number;
            /**
             * Aggregate Specific Gravity
             * @description Gs de l'agrégat (masse volumique spécifique).
             */
            aggregate_specific_gravity: number;
        };
        /**
         * RpgEssaiAdjustment
         * @description Ajustements appliqués à une recette RPG lors de la méthode essai-erreur.
         *     Identique à RpcEssaiAdjustment mais avec un champ agrégat supplémentaire.
         */
        RpgEssaiAdjustment: {
            /**
             * Added Dry Residue Mass
             * @description Masse de résidu sec ajoutée (kg).
             * @default 0
             */
            added_dry_residue_mass: number;
            /**
             * Added Wet Residue Mass
             * @description Masse de résidu humide ajoutée (kg).
             * @default 0
             */
            added_wet_residue_mass: number;
            /**
             * Added Aggregate Mass
             * @description Masse d'agrégat sec ajouté (kg). Spécifique RPG.
             * @default 0
             */
            added_aggregate_mass: number;
            /**
             * Aggregate Moisture Mass Pct
             * @description Teneur en eau massique de l'agrégat ajouté (w0-ag, %). Par défaut 0 (agrégat sec).
             * @default 0
             */
            aggregate_moisture_mass_pct: number;
            /**
             * Added Water Mass
             * @description Masse d'eau ajoutée (kg).
             * @default 0
             */
            added_water_mass: number;
        };
        /**
         * RpgEssaiInputs
         * @description Entrées pour la méthode RPG — Essai-erreur.
         *     Repart d'une recette de base RPG (Cw ou W/C) et applique des ajustements.
         */
        RpgEssaiInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /** @description Méthode de base: CW ou WB. */
            base_method: components["schemas"]["RpcMethod"];
            base_inputs_cw?: components["schemas"]["RpgCwInputs"] | null;
            base_inputs_wb?: components["schemas"]["RpgWbInputs"] | null;
            /**
             * Adjustments
             * @description Liste des ajustements (un par recette).
             */
            adjustments: components["schemas"]["RpgEssaiAdjustment"][];
        };
        /**
         * RpgWbInputs
         * @description Entrées pour la méthode RPG — Rapport eau/ciment (W/C).
         */
        RpgWbInputs: {
            /** @default RPC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            residue: components["schemas"]["ResidueProps"];
            binder_system: components["schemas"]["BinderSystem"];
            /** @description Constantes optionnelles pour personnaliser les calculs. */
            constants?: components["schemas"]["SolverConstants"] | null;
            /**
             * Num Recipes
             * @description Nombre de recettes à calculer (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Containers Per Recipe
             * @description Nombre de contenants par recette.
             * @default 1
             */
            containers_per_recipe: number;
            /**
             * Safety Factor
             * @description Facteur de sécurité appliqué au volume total.
             * @default 1
             */
            safety_factor: number;
            /**
             * Saturation Pct
             * @description Degré de saturation Sr (%).
             */
            saturation_pct: number;
            /**
             * Binder Mass Pct Recipes
             * @description Bw% (liant / (résidu+agrégat)) pour chaque recette.
             */
            binder_mass_pct_recipes: number[];
            /**
             * Wc Ratio Recipes
             * @description Rapport eau/ciment (W/C) pour chaque recette.
             */
            wc_ratio_recipes: number[];
            /**
             * Aggregate Fraction Pct
             * @description A_m% — fraction massique d'agrégat dans les solides non-liant.
             */
            aggregate_fraction_pct: number;
            /**
             * Aggregate Specific Gravity
             * @description Gs de l'agrégat.
             */
            aggregate_specific_gravity: number;
        };
        /**
         * RrcInputs
         * @description Entrées pour le RRC/CRF.
         *
         *     Le mélange est défini par :
         *       - la quantité de CRF : volume de chantier x masse volumique humide,
         *         ou masse totale directe ;
         *       - Bw = Mc/MWR (taux massique de liant par rapport aux roches stériles) ;
         *       - W/C = M*\/Mc (fluide = eau + retardateur, par rapport au ciment) ;
         *       - le dosage du retardateur de prise D0 (ml/100 kg de ciment, 0 = aucun).
         */
        RrcInputs: {
            /** @default RRC */
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            /**
             * Num Recipes
             * @description Nombre de recettes (1 à 4).
             * @default 1
             */
            num_recipes: number;
            /**
             * Quantity Mode
             * @description Quantité de CRF donnée par volume de chantier ou masse totale.
             * @default volume
             * @enum {string}
             */
            quantity_mode: "volume" | "masse";
            /**
             * Volume M3
             * @description Volume du chantier à remblayer (m³) — mode volume.
             */
            volume_m3?: number | null;
            /**
             * Wet Density Kg M3
             * @description Masse volumique humide du CRF (kg/m³) — mode volume.
             * @default 2200
             */
            wet_density_kg_m3: number | null;
            /**
             * Total Mass Kg
             * @description Masse totale de CRF (kg) — mode masse.
             */
            total_mass_kg?: number | null;
            /**
             * Binder Mass Pct Recipes
             * @description Bw% (= Mc/MWR x 100) pour chaque recette.
             */
            binder_mass_pct_recipes: number[];
            /**
             * Wc Ratio Recipes
             * @description Rapport W/C du coulis (fluide/ciment) pour chaque recette.
             */
            wc_ratio_recipes: number[];
            /**
             * Cement Specific Gravity
             * @description Gs du ciment (pour le volume du coulis).
             * @default 3.15
             */
            cement_specific_gravity: number;
            /**
             * Retarder Dosage Ml Per 100Kg
             * @description Dosage du retardateur D0 (ml/100 kg de ciment). 0 = aucun.
             * @default 0
             */
            retarder_dosage_ml_per_100kg: number;
            /**
             * Retarder Density G Ml
             * @description Masse volumique du retardateur (g/ml).
             * @default 1.2
             */
            retarder_density_g_ml: number;
            constants?: components["schemas"]["SolverConstants"] | null;
        };
        /**
         * RrcRecipeState
         * @description Résultat d'une recette RRC/CRF (formules Dias 68-70).
         */
        RrcRecipeState: {
            /** Bw Mass Pct */
            bw_mass_pct: number;
            /** Wc Ratio */
            wc_ratio: number;
            /** W Mass Pct */
            w_mass_pct: number;
            /** Solids Mass Pct */
            solids_mass_pct: number;
            /** Retarder Dosage Mass Pct */
            retarder_dosage_mass_pct: number;
            /** Total Mass Kg */
            total_mass_kg: number;
            /** Crf Volume M3 */
            crf_volume_m3: number;
            /** Waste Rock Mass Kg */
            waste_rock_mass_kg: number;
            /** Cement Mass Kg */
            cement_mass_kg: number;
            /** Fluid Mass Kg */
            fluid_mass_kg: number;
            /** Water Mass Kg */
            water_mass_kg: number;
            /** Retarder Mass Kg */
            retarder_mass_kg: number;
            /** Retarder Volume L */
            retarder_volume_l: number;
            /** Slurry Mass Kg */
            slurry_mass_kg: number;
            /** Slurry Volume M3 */
            slurry_volume_m3: number;
        };
        /**
         * RrcResult
         * @description Résultat global du solveur RRC.
         */
        RrcResult: {
            category: components["schemas"]["MixCategory"];
            general: components["schemas"]["GeneralInfo"];
            /** Recipes */
            recipes: components["schemas"]["RrcRecipeState"][];
        };
        /**
         * SolverConstants
         * @description Constantes numériques optionnelles pour le solveur.
         *     Si non fournies, le backend utilise ses valeurs par défaut.
         */
        SolverConstants: {
            /**
             * Water Density
             * @description Masse volumique de l'eau (kg/m³).
             * @default 1000
             */
            water_density: number;
            /**
             * Gravity
             * @description Accélération de la gravité (m/s²).
             * @default 9.81
             */
            gravity: number;
            /**
             * Slump Small To Large Factor
             * @description Facteur de conversion du petit cône vers le grand cône.
             * @default 2.335
             */
            slump_small_to_large_factor: number;
            /**
             * Slump Model Coeff
             * @description Coefficient du modèle prédictif du slump.
             * @default 4950000
             */
            slump_model_coeff: number;
            /**
             * Slump Model Offset
             * @description Constante additive du modèle prédictif du slump.
             * @default 235.5122
             */
            slump_model_offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rpc_cw_endpoint_rpc_cw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpcCwInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpc_wb_endpoint_rpc_wb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpcWbInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpc_slump_endpoint_rpc_slump_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpcSlumpInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpc_essai_endpoint_rpc_essai_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpcEssaiInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpg_cw_endpoint_rpg_cw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpgCwInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpg_wb_endpoint_rpg_wb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpgWbInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rpg_essai_endpoint_rpg_essai_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RpgEssaiInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixDesignResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rrc_dosage_endpoint_rrc_dosage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RrcInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RrcResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
